*** Starting uWSGI 2.0.20 (64bit) on [Sun Jan  2 13:20:26 2022] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 28 December 2021 16:31:48
os: Linux-3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021
nodename: VM-12-15-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /
detected binary path: /home/lighthouse/productManagement/backend/4bc7979437f34c4a068a749dbdeee4f1_venv/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/lighthouse/productManagement/backend
your processes number limit is 7265
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:12104 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:34048 (port auto-assigned) fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.7 (default, Dec 28 2021, 23:53:48)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x17023a0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
ModuleNotFoundError: No module named 'wsgi'
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "/home/lighthouse/productManagement/backend/backend/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21612)
spawned uWSGI worker 1 (pid: 21613, cores: 2)
spawned uWSGI http 1 (pid: 21614)
--- no python application found, check your startup logs for errors ---
[pid: 21613|app: -1|req: -1/1] 223.73.88.249 () {40 vars in 3230 bytes} [Sun Jan  2 13:20:46 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 21613|app: -1|req: -1/2] 223.73.88.249 () {40 vars in 3190 bytes} [Sun Jan  2 13:20:46 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Sun Jan  2 13:21:43 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
